language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
before_script:
  - cp $TRAVIS_BUILD_DIR/src/config/config.sample.js $TRAVIS_BUILD_DIR/src/config/config.js
script:
  - npm run build
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - dist/*
    - 'package-lock.json'
    - 'package.json'
    - 'README.md'
    - 'LICENSE.md'
  prerelease: false
  draft: true
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: '$TRAVIS_TAG Latest Stable Release'
  on:
    repo: d0p3t/SubNotifier
    branch: master
    tags: true
after_success:
  - wget https://d0p3t.nl/maildelivery/discord.sh
  - chmod +x discord.sh
  - './discord.sh success $WEBHOOK_URL'
after_failure:
  - wget https://d0p3t.nl/maildelivery/discord.sh
  - chmod +x discord.sh
  - './discord.sh failure $WEBHOOK_URL'
after_deploy:
  - wget https://d0p3t.nl/maildelivery/discord.sh
  - chmod +x discord.sh
  - './discord.sh deployed $WEBHOOK_URL'
